[package]
name = "dev"
version = "0.1.1"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = { version = "4.5.26", features = ["derive"] }
env_logger = "0.11.6"
log = "0.4.25"
serde = {version ="1.0.217", features = ["derive"] }
serde_yaml = "0.9.34"
thiserror = "2.0.11"

[dev-dependencies]
proptest = "1.6.0"
proptest-derive = "0.5.1"
