[package]
name = "dev"
version = "0.1.1"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = { version = "4.5.8", features = ["derive"] }
env_logger = "0.11.3"
log = "0.4.22"
serde = {version ="1.0.203", features = ["derive"] }
serde_yaml = "0.9.34"
thiserror = "1.0.62"

[dev-dependencies]
proptest = "1.5.0"
proptest-derive = "0.5.0"
