name: "Test"
permissions: read-all
on:
  pull_request:
  push:
jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@44c2b7a8a4ea60a981eaca3cf939b5f4305c123b
    - uses: cachix/install-nix-action@8887e596b4ee1134dae06b98d573bd674693f47c
      with:
        github_access_token: ${{ secrets.GITHUB_TOKEN }}
    - run: nix build
    - run: nix flake check
    # Run Rudra
    - name: Rudra
      uses: sslab-gatech/Rudra@master
